### ISSUE TITLE
对等节点数据无法复制

### ISSUE THREAD

**Issue by lichenfeng0210** [Rock-520/p2pdb#12]
我们在使用过程中，单机启动了两个实例，端口分别为3306和3307。用navicat连接查看没有任何问题。但是想实现两个实例的数据自动同步功能，一直无法成功，请问有相关的配置文档可以参考吗？期待您的回复，非常感谢。

**Comment by Rock-520** [comment]
感谢你的关注， P2PDB 是一个正在积极研发的去中心化数据库， 对等节点数据同步功能只会在正式版本1.0 中出现，正式版本发布时间可以参考我们规划的[路线图](https://rock-liyi.github.io/p2pdb/#/zh-cn/roadmap ),  如果方便的话，希望能留下一个联系方式，希望能进一步跟你沟通，了解你对P2PDB的使用场景，方便我们在后续的迭代中完善场景

**Comment by lichenfeng0210** [comment]
您好，这是我的联系方式，QQ：823359543；邮箱：lichenfengit@163.com。

**Comment by Rock-520** [comment]
> 

我已经通过邮箱发送我的微信联系方式，咱们加微信沟通， 这个issues我就关闭了哈
